version: 0.0
os: linux
files:
 - source: nginx_files/nginx.conf
   destination: /tmp/
   overwrite: yes
 - source: php_files/php.ini
   destination: /tmp/
   overwrite: yes
 - source: nginx_server/
   destination: /tmp/nginx_server/
 - source: php_files/www.conf
   destination: /tmp/
   overwrite: yes

hooks:
 BeforeInstall:
  - location: scripts/install_dependencies.sh
    timeout: 300
    runas: root
 AfterInstall:
  - location: scripts/conf_app.sh
    timeout: 300
    runas: root
  - location: scripts/conf_nginx.sh
    timeout: 300
    runas: root
  - location: scripts/config_packages.sh
    timeout: 900
    runas: root
  - location: scripts/restart_services.sh
    timeout: 300
    runas: root
